# Site settings
description: A blog of onetwo
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://linonetwo.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lin onetwo
user_description: Lin onetwo @ ShanghaiTech
user_title: Web Developer
email: linonetwo012@gmail.com
facebook_username: linonetwo
github_username:  linonetwo

# Build settings
markdown: kramdown
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false


# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
